const env = {
   "envs":[
      {
         "type":"encrypted",
         "value":"JiftyWzpCVzBJL2Y6gIm6c4qgN7yyNEbYXBQdbMbngYRn2nfw48B1Y/FgfcjdlMHQFrm8SJ794wPdi6u4IRUE4rNnC4xqiz+kPLZOazPlT4eytOrqYEbhqdAOblaoHgpwk/Ef1CqmSY1qBMdqSDJHywwjnB92mfiUf/1lcgSY0LLuDio8tlLQ16uQ4I1XLF3",
         "target":[
            "production",
            "preview",
            "development"
         ],
         "configurationId":"icfg_trVVCTGoQ46LvzWpe6i7AmAw",
         "id":"iqVw2gfC6AwEgehS",
         "key":"MONGODB_URI",
         "createdAt":1689072300864,
         "updatedAt":1689072300864,
         "createdBy":"G2KKqqfZh4agndAeOckgXcqS",
         "updatedBy":null,
         "decrypted":false
      },
      {
         "type":"encrypted",
         "value":"DtnzpxNGf/HYMJhTjGF9CsYeV1PmfF7f+2AjfpGkkWqK8ezji589rn5uDjWqp5RFwFB5kuzlkBb0S2RShPpWnc7BVXltNRQaUn+M6RCG8z8tvZy9Y/MvAJOS/ggsYz4t",
         "target":[
            "production",
            "preview",
            "development"
         ],
         "configurationId":"icfg_trVVCTGoQ46LvzWpe6i7AmAw",
         "id":"7QP5GCZeRpiUNdAV",
         "key":"DATA_API_KEY",
         "createdAt":1689072300863,
         "updatedAt":1689072300863,
         "createdBy":"G2KKqqfZh4agndAeOckgXcqS",
         "updatedBy":null,
         "decrypted":false
      },
      {
         "type":"encrypted",
         "value":"vudWpdHKFPTqZIx486N7TVFUtKNhqNheK1hIetlQvIGZiVbIXQc7FDRj6rfocjtvwLKHv+WE1rkFolpUaB31XxTkikhcM7WLvdC/zcXYbdo=",
         "target":[
            "production",
            "preview",
            "development"
         ],
         "configurationId":"icfg_trVVCTGoQ46LvzWpe6i7AmAw",
         "id":"Gjhj5ccbM0Y30ztk",
         "key":"DATA_API_URL",
         "createdAt":1689072300863,
         "updatedAt":1689072300863,
         "createdBy":"G2KKqqfZh4agndAeOckgXcqS",
         "updatedBy":null,
         "decrypted":false
      }
   ]
}